/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.view;

/**
 *
 * @author oronisaha
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDashboardTitle = new javax.swing.JLabel();
        btnUserManagement = new javax.swing.JButton();
        btnEligibilityCheck = new javax.swing.JButton();
        btnRecoveryPlan = new javax.swing.JButton();
        btnAcademicReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRS - Dashboard");

        lblDashboardTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDashboardTitle.setText("Main Menu");

        btnUserManagement.setText("User Management");
        btnUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManagementActionPerformed(evt);
            }
        });

        btnEligibilityCheck.setText("Eligibility Check");
        btnEligibilityCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEligibilityCheckActionPerformed(evt);
            }
        });

        btnRecoveryPlan.setText("Course Recovery Plan");
        btnRecoveryPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecoveryPlanActionPerformed(evt);
            }
        });

        btnAcademicReport.setText("Academic Report");
        btnAcademicReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcademicReportActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblDashboardTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEligibilityCheck)
                            .addComponent(btnUserManagement)
                            .addComponent(btnRecoveryPlan)
                            .addComponent(btnAcademicReport)
                            .addComponent(btnLogout))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblDashboardTitle)
                .addGap(27, 27, 27)
                .addComponent(btnUserManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEligibilityCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecoveryPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAcademicReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManagementActionPerformed
           System.out.println("User Management clicked"); 
           new UserManagementFrame().setVisible(true);  // open User Management
           this.dispose();                              // close Dashboard
    
    }//GEN-LAST:event_btnUserManagementActionPerformed

    private void btnEligibilityCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEligibilityCheckActionPerformed
        new EligibilityCheckFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEligibilityCheckActionPerformed

    private void btnRecoveryPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecoveryPlanActionPerformed
        new CourseRecoveryPlanFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRecoveryPlanActionPerformed

    private void btnAcademicReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcademicReportActionPerformed
        new AcademicReportFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAcademicReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginFrame().setVisible(true);  // go back to login
        this.dispose();                     // close Dashboard
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcademicReport;
    private javax.swing.JButton btnEligibilityCheck;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRecoveryPlan;
    private javax.swing.JButton btnUserManagement;
    private javax.swing.JLabel lblDashboardTitle;
    // End of variables declaration//GEN-END:variables
}
