/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.view;

import crs.model.Course;
import crs.model.Grade;
import crs.util.CourseDataHelper;
import crs.util.GradeDataHelper;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.File;
/**
 *
 * @author oronisaha
 */
public class AcademicReportFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AcademicReportFrame.class.getName());

    /**
     * Creates new form AcademicReportFrame
     */
    public AcademicReportFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        cmbSemester = new javax.swing.JComboBox<>();
        lblSemester = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnLoadCourses = new javax.swing.JButton();
        scrollCourses = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnGeneratePdf = new javax.swing.JButton();
        btnSendEmail = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRS - Academic Report");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Academic Report");

        lblStudentId.setText("Student ID:");

        txtStudentId.setColumns(15);

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6" }));

        lblSemester.setText("Semester:");

        lblYear.setText("Year: ");

        txtYear.setColumns(15);

        btnLoadCourses.setText("Load Courses");
        btnLoadCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadCoursesActionPerformed(evt);
            }
        });

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course Code", "Course Title", "Credit Hours", "Grade", "Grade Point"
            }
        ));
        scrollCourses.setViewportView(tblCourses);

        btnGeneratePdf.setText("Generate PDF");
        btnGeneratePdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePdfActionPerformed(evt);
            }
        });

        btnSendEmail.setText("Send To Email");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(lblTitle)
                                .addGap(163, 163, 163))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudentId)
                                    .addComponent(lblSemester)
                                    .addComponent(lblYear))
                                .addGap(83, 83, 83)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStudentId)
                                    .addComponent(txtYear)
                                    .addComponent(cmbSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(101, 101, 101))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(btnLoadCourses)
                                .addGap(182, 182, 182))))
                    .addComponent(scrollCourses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnGeneratePdf, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnSendEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentId)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSemester))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLoadCourses)
                .addGap(18, 18, 18)
                .addComponent(scrollCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeneratePdf)
                    .addComponent(btnSendEmail)
                    .addComponent(btnBack))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneratePdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePdfActionPerformed
        
        System.out.println("🟢 Generate PDF button clicked");
        String studentId = txtStudentId.getText().trim();
        String semester = cmbSemester.getSelectedItem().toString();
        String yearText = txtYear.getText().trim();
        
        if (studentId.isEmpty() || yearText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Student ID and Year.");
            return;
        }
        
        int year;
        try {
            year = Integer.parseInt(yearText.replaceAll("[^0-9]", ""));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid year format.");
            return;
        }
        var students = crs.util.StudentDataHelper.loadStudents("student_information.csv");
        crs.model.Student selectedStudent = null;
        for (var s : students) {
            if (s.getStudentId().equalsIgnoreCase(studentId)) {
                selectedStudent = s;
                break;
            }
        }
        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Student not found.");
            return;
        }
        
        crs.controller.AcademicReportController arc = new crs.controller.AcademicReportController();
        boolean ok = arc.generateReport(selectedStudent, semester, year);
        
        if (ok) {
            JOptionPane.showMessageDialog(this, 
                    "PDF generated successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Failed to generate PDF.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnGeneratePdfActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new DashboardFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoadCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadCoursesActionPerformed


    String studentId = txtStudentId.getText().trim();

    if (studentId.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Student ID.");
        return;
    }

    ArrayList<Course> courses = CourseDataHelper.loadCourses("course_assessment_information.csv");
    ArrayList<Grade> grades = GradeDataHelper.loadGrades("student_course_grades.csv");

    DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    model.setRowCount(0);

    for (Grade g : grades) {

        if (g.getStudentId().equals(studentId)) {

            Course matched = null;

            for (Course c : courses) {
                if (c.getCourseCode().equals(g.getCourseId())) {
                    matched = c;
                    break;
                }
            }

            if (matched != null) {
                model.addRow(new Object[]{
                    matched.getCourseCode(),
                    matched.getCourseTitle(),
                    matched.getCreditHours(),
                    g.getGradeLetter(),
                    g.getGradePoint()
                });
            }
        }
    }

    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, 
            "No courses found for this student.");
    }


    
    }//GEN-LAST:event_btnLoadCoursesActionPerformed

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        System.out.println("📧 Send Email button clicked");
    
    String studentId = txtStudentId.getText().trim();
    String semester = cmbSemester.getSelectedItem().toString();
    String yearText = txtYear.getText().trim();
    
    if (studentId.isEmpty() || yearText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Student ID and Year.");
        return;
    }
    
    int year;
    try {
        year = Integer.parseInt(yearText.replaceAll("[^0-9]", ""));
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid year format.");
        return;
    }

    // find the student
    var students = crs.util.StudentDataHelper.loadStudents("student_information.csv");
    crs.model.Student selectedStudent = null;
    for (var s : students) {
        if (s.getStudentId().equalsIgnoreCase(studentId)) {
            selectedStudent = s;
            break;
        }
    }
    if (selectedStudent == null) {
        JOptionPane.showMessageDialog(this, "Student not found.");
        return;
    }

    // generate the PDF (same as Generate PDF button)
    crs.controller.AcademicReportController arc = new crs.controller.AcademicReportController();
    boolean ok = arc.generateReport(selectedStudent, semester, year);

    if (!ok) {
        JOptionPane.showMessageDialog(this, "Failed to generate PDF.");
        return;
    }

    // 🔥 IMPORTANT: build the SAME filename as PdfGenerator
    // Console shows: reports/S002_Sem1_2.pdf
    String semDigits = semester.replaceAll("[^0-9]", "");
    int semNum = semDigits.isEmpty() ? 1 : Integer.parseInt(semDigits);

    String relativePdfPath = "reports/" + studentId + "_Sem" + semNum + "_" + year + ".pdf";
    System.out.println("Computed PDF (relative): " + relativePdfPath);

    try {
        crs.util.EmailSender.sendEmailWithAttachment(
                selectedStudent.getEmail(),
                "Your Academic Report",
                "Dear student,\n\nPlease find your academic report attached.\n\nRegards,\nCRS System",
                relativePdfPath     // <-- NO FileHelper here
        );
        JOptionPane.showMessageDialog(this, "Email sent successfully!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Failed to send email:\n" + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSendEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AcademicReportFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGeneratePdf;
    private javax.swing.JButton btnLoadCourses;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollCourses;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
