/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.view;
import crs.controller.RecoveryPlanController;
import crs.model.RecoveryPlan;
import crs.model.RecoveryTask;
import crs.model.Student;
import crs.model.Grade;

import crs.util.StudentDataHelper;
import crs.util.GradeDataHelper;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oronisaha
 */
public class CourseRecoveryPlanFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CourseRecoveryPlanFrame.class.getName());

    private RecoveryPlanController recoveryController;
    private Student selectedStudent;
    
    public CourseRecoveryPlanFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        recoveryController = new RecoveryPlanController();
        selectedStudent = null;
    }

     
    private void loadFailedComponents() {
        DefaultTableModel model = (DefaultTableModel) tblFailedComponents.getModel();
        model.setRowCount(0);

        if (selectedStudent == null) {
            return;
        }

        ArrayList<Grade> grades = GradeDataHelper.loadGrades("data/student_course_grades.csv");

        for (Grade g : grades) {
            if (g.getStudentId().equals(selectedStudent.getStudentId())
                    && g.getGradePoint() < 2.0) {

                model.addRow(new Object[]{
                    g.getCourseCode(),      // Course
                    g.getComponentName(),   // Component
                    g.getGradePoint()       // Current Grade
                });
            }
        }
    }

    
    private void loadRecoveryTasks() {
        DefaultTableModel model = (DefaultTableModel) tblRecoveryTasks.getModel();
        model.setRowCount(0);

        if (selectedStudent == null) {
            return;
        }

        java.util.List<RecoveryPlan> plans =
                recoveryController.getRecoveryPlansByStudent(selectedStudent.getStudentId());

        for (RecoveryPlan plan : plans) {
            for (RecoveryTask t : plan.getTasks()) {
                model.addRow(new Object[]{
                    plan.getCourseCode(),   // Course
                    t.getWeek(),            // Week
                    t.getDescription(),     // Task Description
                    t.getStatus()           // Status
                });
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        mainPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        btnLoadFailedComponents = new javax.swing.JButton();
        scrollFailedComponents = new javax.swing.JScrollPane();
        tblFailedComponents = new javax.swing.JTable();
        scrollRecoveryTasks = new javax.swing.JScrollPane();
        tblRecoveryTasks = new javax.swing.JTable();
        lblCourse = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        lblWeek = new javax.swing.JLabel();
        txtWeek = new javax.swing.JTextField();
        lblTaskDescription = new javax.swing.JLabel();
        txtTaskDescription = new javax.swing.JTextField();
        btnAddTask = new javax.swing.JButton();
        btnUpdateTask = new javax.swing.JButton();
        btnDeleteTask = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRS - Course Recovery Plan");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Course Recovery Plan");

        lblStudentId.setText("Student ID:");

        txtStudentId.setColumns(10);

        btnLoadFailedComponents.setText("Load Failed Components");
        btnLoadFailedComponents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFailedComponentsActionPerformed(evt);
            }
        });

        tblFailedComponents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course", "Component", "Current Grade"
            }
        ));
        scrollFailedComponents.setViewportView(tblFailedComponents);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblStudentId)
                .addGap(26, 26, 26)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnLoadFailedComponents)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scrollFailedComponents)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentId)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadFailedComponents))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollFailedComponents, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblRecoveryTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course", "Week", "Task Description", "Status"
            }
        ));
        scrollRecoveryTasks.setViewportView(tblRecoveryTasks);

        lblCourse.setText("Course: ");

        txtCourse.setColumns(15);
        txtCourse.setText(" ");

        lblWeek.setText("Week:");

        txtWeek.setColumns(15);

        lblTaskDescription.setText("Task:");

        txtTaskDescription.setColumns(15);

        btnAddTask.setText("Add Task");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        btnUpdateTask.setText("Update Task");
        btnUpdateTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTaskActionPerformed(evt);
            }
        });

        btnDeleteTask.setText("Delete Task");
        btnDeleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTaskActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollRecoveryTasks)
                            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCourse)
                                    .addComponent(lblWeek)
                                    .addComponent(lblTaskDescription))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCourse)
                                    .addComponent(txtWeek)
                                    .addComponent(txtTaskDescription))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateTask, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteTask)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(scrollRecoveryTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourse)
                    .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeek)
                    .addComponent(txtWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaskDescription)
                    .addComponent(txtTaskDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTask)
                    .addComponent(btnUpdateTask)
                    .addComponent(btnDeleteTask)
                    .addComponent(btnBack))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new DashboardFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoadFailedComponentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFailedComponentsActionPerformed
       
        String studentId = txtStudentId.getText().trim();
        
        if (studentId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Student ID.");
            return;
        }
        
        ArrayList<Student> students =
                StudentDataHelper.loadStudents("student_information.csv");
        
        Student found = null;
        for (Student s : students) {
            if (s.getStudentId().equals(studentId)) {
                found = s;
                break;
            }
        }
        
        if (found == null) {
            JOptionPane.showMessageDialog(this, "Student not found.");
            selectedStudent = null;
            ((DefaultTableModel) tblFailedComponents.getModel()).setRowCount(0);
            ((DefaultTableModel) tblRecoveryTasks.getModel()).setRowCount(0);
            return;
        }
        
        selectedStudent = found;
        loadFailedComponents();
        loadRecoveryTasks();
    
    

    }//GEN-LAST:event_btnLoadFailedComponentsActionPerformed

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed

        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Load a student first (Load Failed Components).");
            return;
        }
        
        String course = txtCourse.getText().trim();
        String weekText = txtWeek.getText().trim();
        String desc = txtTaskDescription.getText().trim();
        
        if (course.isEmpty() || weekText.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in Course, Week and Task.");
            return;
        }
        
        int week;
        try {
            week = Integer.parseInt(weekText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Week must be a number.");
            return;
        }
        
        recoveryController.createRecoveryPlan(selectedStudent.getStudentId(), course);
        
        boolean ok = recoveryController.addTask(
                selectedStudent.getStudentId(),
                course,
                week,
                desc
        );
        
        if (ok) {
            JOptionPane.showMessageDialog(this, "Task added.");
            loadRecoveryTasks();
        
        } else {
            JOptionPane.showMessageDialog(this, "Could not add task.");
        }
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void btnDeleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTaskActionPerformed

        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Load a student first.");
            return;
        }
        
        int row = tblRecoveryTasks.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a task to delete.");
            return;
        }
        
        String course = tblRecoveryTasks.getValueAt(row, 0).toString();
        int week = Integer.parseInt(tblRecoveryTasks.getValueAt(row, 1).toString());
        
        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Delete task for course " + course + ", week " + week + "?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );
        
        if (confirm != JOptionPane.YES_OPTION) return;
        
        boolean ok = recoveryController.removeTask(selectedStudent.getStudentId(), course, week);
        
        if (ok) {
            JOptionPane.showMessageDialog(this, "Task deleted.");
            loadRecoveryTasks();
        } else {
            JOptionPane.showMessageDialog(this, "Could not delete task.");
        }
    }//GEN-LAST:event_btnDeleteTaskActionPerformed

    private void btnUpdateTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTaskActionPerformed
        
        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this, "Load a student first.");
            return;
        }
        int row = tblRecoveryTasks.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a task to update.");
            return;
        }
        
        String course = tblRecoveryTasks.getValueAt(row, 0).toString();
        int oldWeek = Integer.parseInt(tblRecoveryTasks.getValueAt(row, 1).toString());
        
        String weekText = txtWeek.getText().trim();
        String desc = txtTaskDescription.getText().trim();
        
        if (weekText.isEmpty() || desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter new Week and Task description.");
            return;
        }
        
        int newWeek;
        try {
            newWeek = Integer.parseInt(weekText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Week must be a number.");
            return;
        }
        
        
        recoveryController.removeTask(selectedStudent.getStudentId(), course, oldWeek);
        recoveryController.addTask(selectedStudent.getStudentId(), course, newWeek, desc);
        
        JOptionPane.showMessageDialog(this, "Task updated.");
        loadRecoveryTasks();
    }//GEN-LAST:event_btnUpdateTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CourseRecoveryPlanFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteTask;
    private javax.swing.JButton btnLoadFailedComponents;
    private javax.swing.JButton btnUpdateTask;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblTaskDescription;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeek;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane scrollFailedComponents;
    private javax.swing.JScrollPane scrollRecoveryTasks;
    private javax.swing.JTable tblFailedComponents;
    private javax.swing.JTable tblRecoveryTasks;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtStudentId;
    private javax.swing.JTextField txtTaskDescription;
    private javax.swing.JTextField txtWeek;
    // End of variables declaration//GEN-END:variables
}
