/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crs.view;

import java.util.ArrayList;

import crs.model.Student;
import crs.controller.EnrollmentController;
import javax.swing.JOptionPane;

import crs.util.CgpaHelper;
import crs.util.CourseDataHelper;
import crs.util.GradeDataHelper;
/**
 *
 * @author oronisaha
 */
public class EligibilityCheckFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EligibilityCheckFrame.class.getName());

    private crs.controller.EnrollmentController enrollmentController;
    private Student selectedStudent;
    /**
     * Creates new form EligibilityCheckFrame
     */
    public EligibilityCheckFrame() {
        initComponents();
        setLocationRelativeTo(null);
        btnProceedEnrolment.setEnabled(false);
        
        enrollmentController = new EnrollmentController(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblStudentId = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        lblCgpaTitle = new javax.swing.JLabel();
        lblCgpaValue = new javax.swing.JLabel();
        lblFailedCoursesTitle = new javax.swing.JLabel();
        lblFailedCoursesValue = new javax.swing.JLabel();
        lblStatusTitle = new javax.swing.JLabel();
        lblStatusValue = new javax.swing.JLabel();
        btnCheckEligibility = new javax.swing.JButton();
        btnProceedEnrolment = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRS - Eligibility Check");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Eligibility Check");

        lblStudentId.setText("Student ID:");

        txtStudentId.setColumns(15);

        lblCgpaTitle.setText("CGPA:");

        lblCgpaValue.setText("                    ");

        lblFailedCoursesTitle.setText("Failed Courses:");

        lblFailedCoursesValue.setText("                    ");

        lblStatusTitle.setText("Eligibility Status:");

        lblStatusValue.setText("   ");

        btnCheckEligibility.setText("Check Eligibility");
        btnCheckEligibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckEligibilityActionPerformed(evt);
            }
        });

        btnProceedEnrolment.setText("Proceed to Enrolment");
        btnProceedEnrolment.setEnabled(false);
        btnProceedEnrolment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedEnrolmentActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(159, 159, 159))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStudentId)
                            .addComponent(lblCgpaTitle)
                            .addComponent(lblFailedCoursesTitle)
                            .addComponent(lblStatusTitle))
                        .addGap(53, 53, 53)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusValue)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtStudentId)
                                .addComponent(lblCgpaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFailedCoursesValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnCheckEligibility)
                        .addGap(18, 18, 18)
                        .addComponent(btnProceedEnrolment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBack)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentId)
                    .addComponent(txtStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCgpaTitle)
                    .addComponent(lblCgpaValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFailedCoursesTitle)
                    .addComponent(lblFailedCoursesValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusTitle)
                    .addComponent(lblStatusValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckEligibility)
                    .addComponent(btnProceedEnrolment)
                    .addComponent(btnBack))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new DashboardFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckEligibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckEligibilityActionPerformed
          String studentId = txtStudentId.getText().trim();
          
          if (studentId.isEmpty()) {
              lblCgpaValue.setText("-");
              lblFailedCoursesValue.setText("-");
              lblStatusValue.setText("Enter Student ID");
              btnProceedEnrolment.setEnabled(false);
              selectedStudent = null;
              return;
          }
          
          selectedStudent = null;
          
          ArrayList<Student> allStudents =
                  crs.util.StudentDataHelper.loadStudents("student_information.csv");
          
          for (Student s : allStudents) {
              if (s.getStudentId().equals(studentId)) {
                  selectedStudent = s;
                  break;
              }
          }
          if (selectedStudent == null) {
              lblCgpaValue.setText("-");
              lblFailedCoursesValue.setText("-");
              lblStatusValue.setText("Student Not Found");
              btnProceedEnrolment.setEnabled(false);
              return;
          }
          var grades = GradeDataHelper.loadGrades("student_course_grades.csv");
          var courses = CourseDataHelper.loadCourses("course_assessment_information.csv");
          
          double cgpa = CgpaHelper.calculateCgpa(
                  
                  selectedStudent.getStudentId(),
                  grades,
                  courses
          );

                  
                  int failedCourses = enrollmentController.getFailedCount(selectedStudent.getStudentId());
                  boolean eligible  = enrollmentController.isEligible(selectedStudent);
                  
                  lblCgpaValue.setText(String.format("%.2f", cgpa));
                  lblFailedCoursesValue.setText(String.valueOf(failedCourses));
                  lblStatusValue.setText(eligible ? "Eligible" : "Not Eligible");
                  btnProceedEnrolment.setEnabled(eligible);

    }//GEN-LAST:event_btnCheckEligibilityActionPerformed

    private void btnProceedEnrolmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedEnrolmentActionPerformed

        if (selectedStudent == null) {
            JOptionPane.showMessageDialog(this,
                    "Please check eligibility first.");
            return;
        }
        
        boolean enrolled = enrollmentController.enrollIfEligible(selectedStudent);
        if (enrolled) {
            JOptionPane.showMessageDialog(this,
                "Student " + selectedStudent.getStudentId() + " has been enrolled.");
        } else {
            JOptionPane.showMessageDialog(this,
                    "Student is not eligible for enrolment.");
        }
    }//GEN-LAST:event_btnProceedEnrolmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EligibilityCheckFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckEligibility;
    private javax.swing.JButton btnProceedEnrolment;
    private javax.swing.JLabel lblCgpaTitle;
    private javax.swing.JLabel lblCgpaValue;
    private javax.swing.JLabel lblFailedCoursesTitle;
    private javax.swing.JLabel lblFailedCoursesValue;
    private javax.swing.JLabel lblStatusTitle;
    private javax.swing.JLabel lblStatusValue;
    private javax.swing.JLabel lblStudentId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
